name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: docker run -it --rm   --name hopingboyz   --device /dev/kvm   -v $PWD/vmdata:/vmdata   -e RAM=8000   -e CPU=4   -e DISK_SIZE=100G   hopingboyz/debain12
      run: docker run -it --rm   --name hopingboyz   --device /dev/kvm   -v $PWD/vmdata:/vmdata   -e RAM=8000   -e CPU=4   -e DISK_SIZE=100G   hopingboyz/debain12
